services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    OSW3\SymfonySupport\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Resources/'